### ISSUE TITLE
Refine `FullSpec` to suit framework use cases

### ISSUE THREAD

**Issue by azriel91** [azriel91/peace#13]
To implement additional functionality in a sensible model, we need to refine the traits.

`git status` is closer to a `diff` command with summarized output. When managing an item, it is often useful to view the current state without comparison to any expected state. For the `peace` framework, separate commands to query current and desired states is a suitable divergence from the git command line interface -- close git parallels are `git show $remote/main` and `git diff HEAD..$remote/main`.

* [x] Rename `StatusFnSpec` to `StateNowFnSpec`, `StatusDesiredFnSpec` to `StateDesiredFnSpec`.
* [x] Add `DiffCmd` to return the difference between `StateNow` and `StateDesired`.
* [ ] Change `EnsureOpSpec::check` to also take in the logical state diff.

**Rationale:**

For a `FullSpec`'s check, it may need `Resources` to be altered by a predecessor's `exec_dry` / `exec`.

* `StatusCommand`: For every `FullSpec`, run `status`, `status_desired`, and `diff`, then output diff.

    However, for `FullSpec` successors, if a predecessor has `Some(Diff)`, it means the successor may not be able to run `status`, as it may require the output of the predecessor to exist, before it can run. e.g. a server must exist before you can check if the file exists on the server.

* `DiffCommand`: For every `FullSpec`, run `status`, `status_desired`, and `diff`, then output diff.
* `EnsureCommand`:

    For every `FullSpec`, run `status`, `status_desired`, `check`, and `exec_dry`/`exec`, before progressing onto the next dependent `FullSpec`.

    The functions must be run in heterogeneous instead of homogeneous batches because `status` from `FullSpec2` may report a more detailed status -- `FullSpec1::exec` may have inserted a `Resource` that `FullSpec2::status` uses and detects a more fine-grained status.

<details>
<summary>Status command</summary>

`StatusCommand` runs the same functions run as `DiffCommand`, just less verbose output.

```yaml
ServerLaunch:
  status: server doesn't exist
  status_desired: server exists
  diff: server is missing

AppTransfer:
  status: since server doesn't exist, cannot detect status, but can infer file doesn't exist
  status_desired: file is on server
  diff: file is not on server

AppUnpack:
  status: since file path doesn't exist, cannot detect status, but can infer app needs to be unpacked
  status_desired: file is unpacked
  diff: file is not unpacked

AppConfigure:
  status: since app installation directory doesn't exist, cannot detect status, but can infer app needs to be configured
  status_desired: app is configured
  diff: app is not configured
```

</details>

<details>
<summary>Ensure command</summary>

```yaml
ServerLaunch:
  status: discovers server doesn't exist
  status_desired: server exists
  diff: server is missing
  check: server is missing, need to launch
  exec_dry: inserts example ip 1.2.3.4 into Resources
  exec: launches server, and inserts ip 1.2.3.4

AppTransfer:
  status: server exists, log in to check file state
  status_desired: file should be transferred to server
  diff: file is not on server
  check: file is not on server, need to transfer
  exec_dry: inserts AppPath("/example/path") into Resources
  exec: ~

AppUnpack:
  check: ~
  exec: ~

AppConfigure:
  check: ~
  exec: ~
```

</details>
