### ISSUE TITLE
`ParamsSpecs`: Make serialized form more concise

### ISSUE THREAD

**Issue by azriel91** [azriel91/peace#184]
Write custom serialization / deserialization code so that we don't get the extra layer of indentation.

Current:

```yaml
app_download: !Value
  value:
    src: https://github.com/azriel91/web_app/releases/download/0.1.1/web_app.tar
    dest: azriel91/web_app/0.1.1/web_app.tar
    marker: null
s3_bucket: !FieldWise
  field_wise_spec:
    name: !Value
      value: azriel-peace-envman-demo-1
    marker: null
```

Desired:

```yaml
app_download: !Value
  src: https://github.com/azriel91/web_app/releases/download/0.1.1/web_app.tar
  dest: azriel91/web_app/0.1.1/web_app.tar
s3_bucket: !FieldWise
  name: !Value
    value: azriel-peace-envman-demo-1
```

Tuple params fieldwise specs are tricky.

Current:

```yaml
something: !FieldWise
  field_wise_spec: !MappingFn
    field_name: _0
    fn_map: Some(Fn(&bool, &u16) -> Option<Vec<u8>>)
    marker: null
```

Desired:

```yaml
something: !FieldWise
  _0: !MappingFn
    fn_map: Some(Fn(&bool, &u16) -> Option<Vec<u8>>)
```
